### ISSUE TITLE
Correct the Timeline

### ISSUE THREAD

**Issue by VARoDeK** [JIITODC/trident#24]
Two events are missing:

1) 10 April, 2020: Release themes for Hackathon by 11:00 am IST. 
2) 12 April, 2020: 10:30 am IST: First Round of Evaluation Begins.

And go through the timeline (Trident Profile) again to see if something is missed:

**Comment by karandevtyagi** [comment]
- [ ] 10 April, 2020: Release themes for Hackathon by 11:00 am IST.

- [ ] 12 April, 2020: 10:30 am IST: First Round of Evaluation Begins.

- [ ] Correct date in FAQ.

- [ ] Change team size to 2-4 in FAQ.

**Comment by arushivii** [comment]
@weirdwiz  This is done right?
