### ISSUE TITLE
A new Nav for "Diversity and Inclusion"

### ISSUE THREAD

**Issue by VARoDeK** [JIITODC/trident#28]
## Diversity and Inclusion: 
Education and collaboration are vital to the future of the Technical ecosystem, and it is imperative to us that everyone in the event that wants to participate feels welcome to do so regardless of gender, gender identity, sexual orientation, disability, race, ethnicity, age, religion or economic status. Our code of conduct `<add-link-to-code-of-conduct>` outlines our expectations for all those who participate in our event, as well as the consequences for unacceptable behavior. 

### Onsite Resources:

1) __ID Cards / Badges__ :  
A Badge will be provided to all the Participants. It is necessary to carry your Badges all the time. 
2) __Communication Stickers__ : 
At Registration, participants can pick up communication stickers to add to their badges. Communication stickers indicate a participant’s requested level of interaction with both other participants and Organizing members.  
    * Green = Open to communicate. 
    * Yellow = Only if you know me, please. 
    * Red = I’m not interested in communicating (or being videotaped or photographed) at this time. 
Please be respectful of attendee communication preferences. 
3) __Pronoun Stickers__ :  
Pick up a pronoun sticker from registration to share your pronouns with other conference attendees. Please be respectful of participants’ pronouns. 
    * He / Him
    * She / Her
    * They / Their
    * Call me by my name

**Comment by rexagod** [comment]
@JIITODC/trident-volunteers PTAL

**Comment by eldracode** [comment]
I am working on this.
@VARoDeK please send code of conduct link.

**Comment by VARoDeK** [comment]
Code of Conduct added in new issue.
