### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by VARoDeK** [JIITODC/trident#29]
# Trident Code of Conduct
Compliant with Code of conduct of [Devfolio](https://devfolio.co/code-of-conduct) and [hackcodeofconduct.org](https://hackcodeofconduct.org/).

---

## The Quick Version

All event participants are expected to behave in accordance with professional standards, with both this Code of Conduct. Our hackathon is dedicated to providing a safe and comfortable environment and harassment-free experience for everyone, regardless of the following:
* Gender
* Gender Identity and Expression
* Age
* Sexual Orientation
* Disability
* Physical Appearance
* Body Size
* Race
* Ethnicity
* Nationality
* Religion
* Political Views
* Previous Hackathon attendance or lack of computing experience or lack of chosen programming language or tech stack

---

We do not tolerate harassment of hackathon participants in any form. Sexual language and imagery is not appropriate at any hackathon venue, this includes the following :

* Hacks
* Talks, Presentations, or Demos
* Workshops
* Any parties associated to the Hackathon
* Social Media
* Any other online media

---

We will not tolerate any kind of activities, from participants, mentioned below : 

* Intimate Activities (Kissing, Sexual acts and proximity)
* Consumption of Alcoholic Beverages
* Consumption of Tobacco
* Violent Acts
* Physical and Emotional Abuse

We are free to report such things to your Institution or Police or both (whichever is applicable).

---

## Consequences of Violating Rules

Hackathon participants violating these rules __may be sanctioned or expelled__ from the hackathon __without a refund (if applicable)__ at the discretion of the hackathon organisers.

---

## The Less Quick Version

Harassment includes offensive verbal comments related to gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, nationality, religion or political views, sexual images in public spaces, deliberate intimidation, stalking, following, photography or audio/video recording against reasonable consent, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention.

---

Photography is encouraged, but other participants must be given a reasonable chance to opt out from being photographed. If they object to the taking of their photograph, comply with their request. It is inappropriate to take photographs in contexts where people have a reasonable expectation of privacy (in bathrooms or where participants are sleeping).

---

Participants asked to stop any harassing behavior are expected to comply immediately.

---

As this is a hackathon, we like to explicitly note that the hacks created at our hackathon are equally subject to the anti-harassment policy.

---

Sponsors and partners are also subject to the anti-harassment policy. In particular, sponsors should not use sexualised images, activities, or other material. Sponsor representatives (including volunteers) should not use sexualised clothing/uniforms/costumes, or otherwise create a sexualised environment.

---

If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact a member of hackathon staff immediately.

---

Hackathon staff will be happy to help participants contact any local security or local law enforcement, provide escorts, or otherwise assist those experiencing harassment to feel safe for the duration of the hackathon. We value your attendance.

---

If a participant engages in harassing behavior, the hackathon organisers may take any action they deem appropriate. This includes warning the offender, expulsion from the hackathon with no refund (if applicable), or reporting their behaviour to local law enforcement.

---

We expect participants to follow these rules at hackathon and workshop venues and Hackathon-related social events.

---

All participants and attendees should respect the privacy and space of others. They should respect the participant’s requested level of interaction as indicated by their communication sticker. They are expected to be respectful of participants’ pronouns.

---

Participants should not damage any property of the venue, else, in that case, they are liable to pay fine and may also get expelled from the hackathon.

---

Participants are expected to follow the timeline of the event, strictly. No extensions or special permission will be given to any team or participant for completing the given task. The miniature changes to the timeline are subject to real-time situations at the event.

---

Participants found in getting involved with any intimate activities (Kissing and Sexual acts and proximity) are questionable to the Organizing Team and other Staff. No such acts will be tolerated __inside the premises__. 

---

Participants found consuming Alcoholic Beverages and Tobacco or found involving in Physical abuse and Violent acts will be disqualified immediately and will face the required consequences.

---

## What To Do If You Witness or Are Subject To Unacceptable Behavior

If you are being harassed, notice that someone else is being harassed, or have any other concerns relating to any rule mentioned above, please contact a member of organizing committee immediately. Organizing member can be identified by t-shirts/staff badges onsite, and an organizer can be found at the event registration counter at any time.

---

**Comment by rexagod** [comment]
@eldraco19 I have dropped #32's changes for now due to the fact that the content below was not present. No worries, though, just add those and push again from your remote so we can get to merging #32!

```
We will not tolerate any kind of activities, from participants, mentioned below : 

* Intimate Activities (Kissing, Sexual acts and proximity)
* Consumption of Alcoholic Beverages
* Consumption of Tobacco
* Violent Acts
* Physical and Emotional Abuse

We are free to report such things to your Institution or Police or both (whichever is applicable).

---

## Consequences of Violating Rules

Hackathon participants violating these rules __may be sanctioned or expelled__ from the hackathon __without a refund (if applicable)__ at the discretion of the hackathon organisers.

```
