### ISSUE TITLE
Change in content

### ISSUE THREAD

**Issue by karandevtyagi** [JIITODC/trident#3]
We need new content for this part of the website.

![issue1](https://user-images.githubusercontent.com/40595692/76547025-836aeb00-64b2-11ea-9eaa-9fc8343c289f.PNG)

**Comment by koderjoker** [comment]
Already included in the content I provided 3 days ago.

The first paragraph is supposed to be in the green section of the website while the other paragraphs are to be included in the peach section.

As per @Ankk98 if we are to keep the section with the images and the paragraphs below them then they are to include the vision and goals of our hackathon, and is to be discussed on our WhatsApp group with everyone. (check out the comments in the document for reference)

**Comment by karandevtyagi** [comment]
Basic goal and vision is discussed on the group.We now need proper content to go on website.

**Comment by koderjoker** [comment]
No group discussion has taken place yet regarding the to be listed final vision and goals. Check the WhatsApp group.

**Comment by karandevtyagi** [comment]
Check the doc by Ankit sir

**Comment by koderjoker** [comment]
What Ankit sir has talked about in the doc is already a part of the introductory para, so it'll only be a 1-2 line extension to what I've already provided. Won't be a part of the image-para section.

**Comment by koderjoker** [comment]
Will talk about it with you off GitHub.

**Comment by koderjoker** [comment]
Opened relevant issue #6
