### ISSUE TITLE
Change of links

### ISSUE THREAD

**Issue by karandevtyagi** [JIITODC/trident#4]
Direct links to JODC's offical pages and remove instagram block.

![issue2](https://user-images.githubusercontent.com/40595692/76677253-2bd39900-65f2-11ea-8b82-08314e6aacbf.PNG)

**Comment by Ankurk99** [comment]
On it

**Comment by Ankurk99** [comment]
What's the medium link?

**Comment by rexagod** [comment]
None. Leave an `href="#"` there for now.

**Comment by rexagod** [comment]
Actually remove medium too. Reduce this to just 3 blocks ig.

**Comment by Ankurk99** [comment]
Okay cool, for telegram we need to make a group first.

**Comment by eldracode** [comment]
fixed in #8
