### ISSUE TITLE
Link to "what is a hackathon?" and "why one should participate?"

### ISSUE THREAD

**Issue by Ankk98** [JIITODC/trident#47]
A lot of people will be visiting the website who don't know about the hackathon.
So, eighter make the word "hackathon" (In "what?" section) clickable which leads to any good website explaining what is a hackathon and why one should be participating in it or add these questions in the faqs.

**Comment by rexagod** [comment]
@JIITODC/trident-volunteers PTAL

**Comment by eldracode** [comment]
I added a link in the "What?" section explaining about hackathons.
