### ISSUE TITLE
Change Background Color-Theme

### ISSUE THREAD

**Issue by VARoDeK** [JIITODC/trident#9]
Shift to dark background. Make it compliant with the color of our logo (black).

**Comment by eldracode** [comment]
@VARoDeK @karandevtyagi I did a dark theme revamp, check 
https://tridentfork.netlify.com/

tell me if there's anything to change

**Comment by karandevtyagi** [comment]
@eldraco19 

- Panel looks odd 

- can you do something with timeline to make it better

- change trident logo in footer

**Comment by Ankk98** [comment]
@eldraco19 
- [ ] Fix navbar

Try rounded edges in inner boxes in the timeline and see.

**Comment by karandevtyagi** [comment]
> Shift to dark background. Make it compliant with the color of our logo (black).

Now it looks good.Good work
